[[redirects]]
  from = "/"
  to = "https://mshome.netlify.app/"
  status = 200
  force = true
  
[[redirects]]
  from = "/blog"
  to = "https://msblog.netlify.app/blog"
  status = 200
  force = true
  
[[redirects]]
  from = "/blog/*"
  to = "https://msblog.netlify.app/blog/:splat"
  status = 200
  force = true
