[[redirects]]
  from = "/home"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "https://msblog.netlify.app/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/blog"
  to = "https://msblog.netlify.app/blog"
  status = 200
  force = false
  
[[redirects]]
  from = "/blog/*"
  to = "https://msblog.netlify.app/blog/:splat"
  status = 200
  force = false 
