[[redirects]]
  from = "/"
  to = "https://mshome.netlify.app/"
  status = 200
  force = false

[[redirects]]
  from = "/*"
  to = "https://msblog.netlify.app/blog/:splat"
  status = 200
  force = false
