[[redirects]]
  from = "/blog"
  to = "https://msblog.netlify.app"
  status = 200
  force = true

[[redirects]]
  from = "/blog/*"
  to = "https://msblog.netlify.app/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/blog/static/*"
  to = "https://msblog.netlify.app/static/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/home"
  to = "/"
  status = 200
  force = true
  
  [[redirects]]
  from = "/static/*"
  to = "/static/:splat"
  status = 200
  force = true
