[[redirects]]
  from = "/home"
  to = "/"
  status = 200
  force = true

[[redirects]]
  from = "/blog"
  to = "https://msblog.netlify.app/blog"
  status = 301
  force = true

[[redirects]]
  from = "/blog/*"
  to = "https://msblog.netlify.app/blog/:splat"
  status = 301
  force = true
 
