[[redirects]]
  from = "/static/*"
  to = "/static/:splat"
  status = 200

[[redirects]]
  from = "/home"
  to = "/"
  status = 200
  force = true

[[redirects]]
  from = "/blog"
  to = "https://msblog.netlify.app"
  status = 200
  force = true
