[[redirects]]
  from = "/blog"
  to = "https://msblog.netlify.app/blog/"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "https://msblog.netlify.app/blog/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/blog/static/*"
  to = "https://msblog.netlify.app/blog/static/:splat"
  status = 200

[[redirects]]
  from = "/home"
  to = "/"
  status = 200
  force = true
