[[redirects]]
  from = "/blog/*"
  to = "https://msnotes.netlify.app/blog/:splat"
  status = 200
  force = true
  
[[redirects]]
  from = "/static/*"
  to = "https://msnotes.netlify.app/static/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/blog"
  to = "https://msnotes.netlify.app/blog"
  status = 200
  force = true
   
[[redirects]]
  from = "/home"
  to = "/"
  status = 200
  force = true
